name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=localhost --user=root --password=rootpassword" --health-interval=10s --health-retries=3 --health-start-period=5s

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r practice/app/requirements.txt

    - name: Run tests
      run:
        # Add any commands to run your tests
        curl --fail http://localhost:5000/health || exit 1

    - name: Docker Build and Test
      run:
        docker-compose -f docker-compose.yml up --build -d
        sleep 10 # Wait for the services to initialize
        docker-compose ps
        curl --fail http://localhost:5000/health || exit 1

